### PR TITLE
Print the generated access token

### PR DESCRIPTION
**Pull request by Siilwyn**
Instead of printing just a message that it is created actually print the generated access token to clarify it worked.

### CODE REVIEW

**Comment by adnasa** [comment]
👍

**Comment by schleichardt** [comment]
I am not sure if we should expose our credentials.

**Comment by Siilwyn** [comment]
Good point but even without printing, the initial command contains all data needed to get the access token. Also the token gets written to a file by default.

**Comment by Siilwyn** [comment]
More thoughts on this @schleichardt?
The command itself contains all needed information to get the token so I don't see any harm into printing it, especially not since the output won't be saved in the bash history. Looking to either close or merge this old PR. :)

**Comment by hajoeichler** [comment]
I just checked the travis output. It of course contains the token. But the log does not contain the project key nor any other information. So I am fine with that.

**Pull request merged**
